# Generated by Django 4.2.10 on 2025-07-02 09:30

from django.db import migrations
from django.contrib.auth.hashers import make_password
from django.utils import timezone
import datetime

def create_initial_data(apps, schema_editor):
    # Get models
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('music', 'Profile')
    Artist = apps.get_model('music', 'Artist')
    Genre = apps.get_model('music', 'Genre')
    Album = apps.get_model('music', 'Album')
    Song = apps.get_model('music', 'Song')
    Playlist = apps.get_model('music', 'Playlist')
    PlaylistSong = apps.get_model('music', 'PlaylistSong')
    
    # Create admin user
    admin_user = User.objects.create(
        username='admin',
        email='admin@example.com',
        password=make_password('admin123'),
        is_staff=True,
        is_superuser=True,
        first_name='Admin',
        last_name='User',
        is_active=True
    )
    
    # Create a regular user
    user = User.objects.create(
        username='user',
        email='user@example.com',
        password=make_password('user123'),
        first_name='Regular',
        last_name='User',
        is_active=True
    )
    
    # Create genres
    rock = Genre.objects.create(name='Rock', description='Rock music is a broad genre of popular music that originated as "rock and roll" in the United States in the late 1940s and early 1950s.')
    pop = Genre.objects.create(name='Pop', description='Pop music is a genre of popular music that originated in its modern form during the mid-1950s in the United States and the United Kingdom.')
    jazz = Genre.objects.create(name='Jazz', description='Jazz is a music genre that originated in the African-American communities of New Orleans, Louisiana, in the late 19th and early 20th centuries.')
    electronic = Genre.objects.create(name='Electronic', description='Electronic music is music that employs electronic musical instruments, digital instruments, or circuitry-based music technology.')
    classical = Genre.objects.create(name='Classical', description='Classical music is art music produced or rooted in the traditions of Western culture, including both liturgical and secular music.')
    
    # Create artists
    artist1 = Artist.objects.create(
        name='The Beatles',
        bio='The Beatles were an English rock band formed in Liverpool in 1960.',
        image='beatles.jpg',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    artist2 = Artist.objects.create(
        name='Queen',
        bio='Queen are a British rock band formed in London in 1970.',
        image='queen.jpg',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    artist3 = Artist.objects.create(
        name='Miles Davis',
        bio='Miles Dewey Davis III was an American jazz trumpeter, bandleader, and composer.',
        image='miles_davis.jpg',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    artist4 = Artist.objects.create(
        name='Daft Punk',
        bio='Daft Punk were a French electronic music duo formed in 1993 in Paris.',
        image='daft_punk.jpg',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    # Create albums
    album1 = Album.objects.create(
        title='Abbey Road',
        artist=artist1,
        cover_image='abbey_road.jpg',
        release_date=datetime.date(1969, 9, 26),
        description='Abbey Road is the eleventh studio album by the English rock band the Beatles.',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    album2 = Album.objects.create(
        title='A Night at the Opera',
        artist=artist2,
        cover_image='night_at_the_opera.jpg',
        release_date=datetime.date(1975, 11, 21),
        description='A Night at the Opera is the fourth studio album by the British rock band Queen.',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    album3 = Album.objects.create(
        title='Kind of Blue',
        artist=artist3,
        cover_image='kind_of_blue.jpg',
        release_date=datetime.date(1959, 8, 17),
        description='Kind of Blue is a studio album by American jazz trumpeter Miles Davis.',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    album4 = Album.objects.create(
        title='Random Access Memories',
        artist=artist4,
        cover_image='random_access_memories.jpg',
        release_date=datetime.date(2013, 5, 17),
        description='Random Access Memories is the fourth studio album by French electronic music duo Daft Punk.',
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    # Create songs
    song1 = Song.objects.create(
        title='Come Together',
        artist=artist1,
        album=album1,
        genre=rock,
        file_path='come_together.mp3',
        duration=259,
        cover_image='abbey_road.jpg',
        release_date=datetime.date(1969, 9, 26),
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    song2 = Song.objects.create(
        title='Something',
        artist=artist1,
        album=album1,
        genre=rock,
        file_path='something.mp3',
        duration=182,
        cover_image='abbey_road.jpg',
        release_date=datetime.date(1969, 9, 26),
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    song3 = Song.objects.create(
        title='Bohemian Rhapsody',
        artist=artist2,
        album=album2,
        genre=rock,
        file_path='bohemian_rhapsody.mp3',
        duration=355,
        cover_image='night_at_the_opera.jpg',
        release_date=datetime.date(1975, 10, 31),
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    song4 = Song.objects.create(
        title='Love of My Life',
        artist=artist2,
        album=album2,
        genre=rock,
        file_path='love_of_my_life.mp3',
        duration=219,
        cover_image='night_at_the_opera.jpg',
        release_date=datetime.date(1975, 11, 21),
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    song5 = Song.objects.create(
        title='So What',
        artist=artist3,
        album=album3,
        genre=jazz,
        file_path='so_what.mp3',
        duration=547,
        cover_image='kind_of_blue.jpg',
        release_date=datetime.date(1959, 8, 17),
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    song6 = Song.objects.create(
        title='Get Lucky',
        artist=artist4,
        album=album4,
        genre=electronic,
        file_path='get_lucky.mp3',
        duration=248,
        cover_image='random_access_memories.jpg',
        release_date=datetime.date(2013, 4, 19),
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    # Create playlists
    playlist1 = Playlist.objects.create(
        title='Rock Classics',
        user=admin_user,
        description='The best rock songs of all time',
        cover_image='rock_classics.jpg',
        is_public=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    playlist2 = Playlist.objects.create(
        title='Chill Vibes',
        user=user,
        description='Relaxing songs for a chill day',
        cover_image='chill_vibes.jpg',
        is_public=True,
        created_at=timezone.now(),
        updated_at=timezone.now()
    )
    
    # Add songs to playlists
    PlaylistSong.objects.create(
        playlist=playlist1,
        song=song1,
        added_at=timezone.now(),
        order=1
    )
    
    PlaylistSong.objects.create(
        playlist=playlist1,
        song=song3,
        added_at=timezone.now(),
        order=2
    )
    
    PlaylistSong.objects.create(
        playlist=playlist2,
        song=song5,
        added_at=timezone.now(),
        order=1
    )
    
    PlaylistSong.objects.create(
        playlist=playlist2,
        song=song6,
        added_at=timezone.now(),
        order=2
    )

def delete_initial_data(apps, schema_editor):
    # Delete all created data
    User = apps.get_model('auth', 'User')
    User.objects.filter(username__in=['admin', 'user']).delete()
    
    # The rest of the data will be deleted via cascade

class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, delete_initial_data),
    ]
